feat: face_area
t4t5u0/PatternRecognition pull request #2
Opened 2021-07-23 20:49 UTC by kota-shiokara

- [x] グレースケールにする 
- [x] 顔領域を取得
- [x] 出力はtuple

2021-07-23 20:50 UTC, kota-shiokara commented
img: 画像を格納しとく
model: 分類機入れとく

2021-07-23 23:41 UTC, t4t5u0 requested changes
か縫うfaceArea内で `tmp` を返却してるのはやばいと思います。`result` などが適切ではないでしょうか

2021-07-24 06:52 UTC, kota-shiokara commented
変数名とかごっつてきとうにやってた
どうせローカル変数だしって

2021-07-25 02:58 UTC, kota-shiokara commented
@t4t5u0 マージするかChanges requestするかしてほしいんだぜ

2021-07-25 03:25 UTC, t4t5u0 approved these changes
LGTM

2021-07-25 03:25 UTC, merged